apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: flask
  template:
    metadata: 
      labels:
        app: flask 
    spec:
      containers:
      - name: devsecops
        image: harbeylefty17/devsecops
        ports:
        - containerPort: 5000
        resources: 
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
apiVersion: v1 
kind: Service
metadata: 
  name: flask-app-service
spec:
  type: LoadBalancer
  selector: 
    app: flask
  ports:
  - protocol: TCP 
    port: 80
    targetPort: 5000
